// DAX Query
DEFINE
	VAR __DS0FilterTable = 
		TREATAS({"South"}, 'States'[Census Region])

	VAR __DS0Core = 
		FILTER(
			KEEPFILTERS(
				SUMMARIZECOLUMNS(
					'States'[Census Region],
					'States'[Census Division],
					'States'[State],
					'States'[Abbreviation],
					'States'[2015 population],
					__DS0FilterTable,
					"MinCensus_Region", IGNORE(CALCULATE(MIN('States'[Census Region])))
				)
			),
			OR(
				OR(
					OR(
						OR(
							NOT(ISBLANK('States'[Census Region])),
							NOT(ISBLANK('States'[Census Division]))
						),
						NOT(ISBLANK('States'[State]))
					),
					NOT(ISBLANK('States'[Abbreviation]))
				),
				NOT(ISBLANK('States'[2015 population]))
			)
		)

	VAR __DS0PrimaryWindowed = 
		TOPN(
			501,
			__DS0Core,
			'States'[2015 population],
			1,
			'States'[Census Region],
			1,
			'States'[Census Division],
			1,
			'States'[State],
			1,
			'States'[Abbreviation],
			1
		)

EVALUATE
	__DS0PrimaryWindowed

ORDER BY
	'States'[2015 population],
	'States'[Census Region],
	'States'[Census Division],
	'States'[State],
	'States'[Abbreviation]
